default:
  image: node:22-alpine
  before_script:
    - corepack enable

stages:
  - build
  - release

cache:
  key: modules
  paths:
    - node_modules/
    - .yarn/cache/
    - dist/

build:
  stage: build
  script:
    - yarn install
    - yarn build

release:
  stage: release
  script:
    - yarn release
