image: node:22-alpine

stages:
  - build
  - publish

cache:
  key: modules
  paths:
    - node_modules/
    - .yarn/cache/
    - dist/

build:
  stage: build
  script:
    - yarn install
    - yarn build

publish:
  stage: publish
  only:
    - tags
  script:
    - yarn config set npmAuthToken $NPM_AUTH_TOKEN
    - yarn npm publish --access public
